ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
  0%|          | 0/4000 [00:00<?, ?it/s]  0%|          | 0/4000 [00:15<?, ?it/s]
Traceback (most recent call last):
  File "/scratch/ask9126/DL_Project22/SimCLR/run.py", line 89, in <module>
    main()
  File "/scratch/ask9126/DL_Project22/SimCLR/run.py", line 85, in main
    simclr.train(train_loader)
  File "/scratch/ask9126/DL_Project22/SimCLR/simclr.py", line 82, in train
    features = self.model(images)
  File "/ext3/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/ask9126/DL_Project22/SimCLR/models/resnet_simclr.py", line 30, in forward
    return self.backbone(x)
  File "/ext3/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/torchvision/models/resnet.py", line 283, in forward
    return self._forward_impl(x)
  File "/ext3/miniconda3/lib/python3.9/site-packages/torchvision/models/resnet.py", line 272, in _forward_impl
    x = self.layer2(x)
  File "/ext3/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/ext3/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/torchvision/models/resnet.py", line 153, in forward
    out = self.bn3(out)
  File "/ext3/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/ext3/miniconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 2421, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 392.00 MiB (GPU 0; 15.78 GiB total capacity; 14.04 GiB already allocated; 106.25 MiB free; 14.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
